if: type != push

language: julia
os:
  - linux
julia:
  - "1.3"
  - "1"
  - nightly
matrix:
  allow_failures:
    - julia: nightly
#before_script: julia --project=.ci/ -e 'using Pkg; Pkg.instantiate()'
before_script: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(name = "RegistryCI", rev = "dpa/automerge-registry-deps"))'
#script: julia --project=.ci/ --color=yes -e 'import RegistryCI; RegistryCI.test(registry_deps = ["https://github.com/JuliaRegistries/General.git"])'
script: julia --color=yes -e 'import RegistryCI; RegistryCI.test(registry_deps = ["https://github.com/JuliaRegistries/General.git"])'
branches:
  only:
    - master
notifications:
  email: false
git:
  depth: 99999999
